<?

// // This file is generated by Composer
// require_once 'vendor/autoload.php';

// $git_name = $_POST['git_name'];
// $user = 'USER_NAME';
// $password = 'USER_PASSWORD';
// $token = 'USER_TOKEN';

// $client = new \Github\Client();
// $repositories = $client->authenticate($token, '', Github\Client::AUTH_HTTP_TOKEN);

// $repo = $client->api('repo')->create($git_name, 'This is the description of a repo', 'http://my-repo-homepage.org', true);

// echo $repo;

?>


<?php

// // This file is generated by Composer
// require_once 'vendor/autoload.php';

// $git_name = $_POST['git_name'];
// $user = 'USER_NAME';
// $password = 'USER_PASSWORD';
// $token = 'USER_TOKEN';


// $client = new \Github\Client();

// $asd = $client->authenticate($token, '', Github\Client::AUTH_HTTP_TOKEN);

// $repo = $client->api('current_user')->repositories();

// $repos = $client->api('user')->repositories($user);

// $repo = $client->api('repo')->create($git_name, 'This is the description of a repo', 'http://example.com', true);

// $repos = $client->api('user')->repositories($user);

// $repo = $client->api('repo')->show($user, 'bitrix-lessons');

// $repos = $client->api('user')->repositories($user)->all();

// echo $repos;
// echo '<br>';
// echo $repo;

?>